# Generated by Django 5.2.7 on 2025-11-21 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bsf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_ean', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_dun', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_sistema', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=350, null=True)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('pack', models.IntegerField(blank=True, null=True)),
                ('factorx', models.FloatField(blank=True, null=True)),
                ('cajas', models.IntegerField(blank=True, null=True)),
                ('saldo', models.IntegerField(blank=True, null=True)),
                ('stock_fisico', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, max_length=350, null=True)),
                ('fecha_inv', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('encargado', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_venc', models.DateField(blank=True, null=True)),
                ('fecha_imp', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('numero_contenedor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
